controller_manager:
  ros__parameters:
    update_rate: 1000  
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    gains:
      shoulder_1_joint: {p: 1000.0, i: 0.0, d: 10.0} 
      shoulder_2_joint: {p: 1000.0, i: 0.0, d: 10.0}
      elbow_joint:      {p: 500.0,  i: 0.0, d: 5.0}
      wrist_1_joint:    {p: 100.0,  i: 0.0, d: 1.0}
      wrist_2_joint:    {p: 100.0,  i: 0.0, d: 1.0}
      wrist_3_joint:    {p: 100.0,  i: 0.0, d: 1.0}

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 1000.0     # Default: 50 Hz
    action_monitor_rate: 1000.0    # Default: 20 Hz
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0


ros2_control:
  ros__parameters:
    use_sim_time: true

    robot_hardware:
      type: gazebo_ros2_control/GazeboSystem
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
